version: '3'

services:
  wordpress:
    image: bitnami/wordpress:latest
    restart: always
    env_file:
      - .env.wordpress
    volumes:
      - wordpress_data:/bitnami/wordpress
      - ./wordpress/upload.ini:/opt/bitnami/php/etc/conf.d/uploads.ini
    depends_on:
      - db
    ports:
      - "80:8080"

  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env.mysql
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/wordpress/wordpress-data
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/wordpress/mysql-data
  