version: '3.8'
services: 
  
  wordpress:
    image: wordpress:5.8.0-php7.4-fpm-alpine
    container_name: wordpress
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: joewalker
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
  
  mariadb:
    image: mariadb:10.6.4-focal
    container_name: mariadb
    platform: linux/amd64
    volumes: 
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wordpress
      MYSQL_USER: joewalker
      MYSQL_PASSWORD: wordpress
  
  nginx:
    image: nginx:stable
    container_name: nginx
    platform: linux/amd64
    ports: 
      - 8080:80
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress
      - mariadb
